Set Login

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -21,8 +21,12 @@ jobs:
 
       - name: Login to Docker Hub
         run: |
-          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
-
+            if [[ -z "${{ secrets.DOCKERHUB_USERNAME }}" || -z "${{ secrets.DOCKERHUB_TOKEN }}" ]]; then
+              echo "Docker Hub credentials are missing. Please set them in the repository secrets."
+              exit 1
+            fi
+            docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
+      
       - name: Build and push Docker image
         run: |
           docker buildx build -t camileite/gelatosavelas:${GITHUB_SHA} .
